# Generated by Django 3.2.5 on 2021-07-02 20:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PartTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('footprint', models.CharField(blank=True, max_length=50, null=True)),
                ('package', models.CharField(blank=True, max_length=50, null=True)),
                ('stock', models.IntegerField(default=0)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('datasheet', models.URLField(blank=True, null=True)),
                ('photo_thumbnail', models.ImageField(blank=True, upload_to='photos/thumbnails/')),
                ('part_of_project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.projects')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.parttypes')),
            ],
        ),
    ]
