# Generated by Django 3.2.5 on 2021-07-02 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_rename_part_parts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subtypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtype', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='parts',
            name='subtypes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.subtypes'),
        ),
    ]
