# Generated by Django 3.2.5 on 2021-07-02 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_parts_value'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Parts',
            new_name='Part',
        ),
        migrations.RenameModel(
            old_name='PartTypes',
            new_name='PartType',
        ),
        migrations.RenameModel(
            old_name='Projects',
            new_name='Project',
        ),
        migrations.RenameModel(
            old_name='Subtypes',
            new_name='Subtype',
        ),
        migrations.RenameModel(
            old_name='Units',
            new_name='Unit',
        ),
    ]
