# Generated by Django 3.2.5 on 2021-07-02 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_rename_subtypes_part_subtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='photo_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='photos/thumbnails/'),
        ),
    ]
