# Generated by Django 3.2.5 on 2021-07-02 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_part_photo_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
