# Generated by Django 3.2.5 on 2021-07-03 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_part_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
