# Generated by Django 3.2.5 on 2021-07-04 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_part_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='part_of_project',
        ),
    ]
